/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { CustomNode } from "./index";

// @ts-ignore
export function nodeTemplateHtml(this: CustomNode) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('span',[_c('span',{class:_vm.color},[_vm._v(_vm._s(_vm.data.value.line))]),_vm._v(_vm._s(_vm.data.value.text))])}
// tslint:enable
