// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, createTextVNode as _createTextVNode, createVNode as _createVNode, Fragment as _Fragment, openBlock as _openBlock, renderList as _renderList, resolveComponent as _resolveComponent, toDisplayString as _toDisplayString } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  const _component_tree = _resolveComponent("tree")

  return (_openBlock(), _createBlock("div", null, [
    _createVNode(_component_tree, {
      data: _ctx.data,
      onToggle: _cache[1] || (_cache[1] = $event => (_ctx.toggle($event))),
      onChange: _cache[2] || (_cache[2] = $event => (_ctx.change($event)))
    }, null, 8 /* PROPS */, ["data"]),
    _createVNode("div", { class: "file" }, _toDisplayString(_ctx.file), 1 /* TEXT */),
    _createVNode("div", {
      ref: "lineNumber",
      class: "line-number"
    }, [
      (_openBlock(true), _createBlock(_Fragment, null, _renderList(_ctx.lineNumbers, (lineNumber) => {
        return (_openBlock(), _createBlock("div", {
          class: lineNumber.className,
          key: lineNumber.lineNumber
        }, _toDisplayString(lineNumber.lineNumber), 3 /* TEXT, CLASS */))
      }), 128 /* KEYED_FRAGMENT */))
    ], 512 /* NEED_PATCH */),
    _createVNode("pre", {
      ref: "code",
      innerHTML: _ctx.selectedNodeText,
      onScroll: _cache[3] || (_cache[3] = $event => (_ctx.scroll($event)))
    }, null, 40 /* PROPS, HYDRATE_EVENTS */, ["innerHTML"])
  ]))
}
export function nodeTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("span", null, [
    _createVNode("span", { class: _ctx.color }, _toDisplayString(_ctx.data.value.line), 3 /* TEXT, CLASS */),
    _createTextVNode(" " + _toDisplayString(_ctx.data.value.text), 1 /* TEXT */)
  ]))
}
/* eslint-enable */
// tslint:enable
